---
  extends: "eslint:recommended"
  plugins:
    - "jsdoc"
    - "node"
  env:
    node: true
  rules:
    node/no-missing-import: 2
    node/no-missing-require: 2
    node/no-unpublished-import: 2
    node/no-unpublished-require: 1
    node/no-unsupported-features:
      - 2
      -
        version: 4
    node/shebang: 2
    jsdoc/check-param-names: 1
    jsdoc/check-tag-names: 1
    jsdoc/check-types: 1
    jsdoc/newline-after-description: 1
    jsdoc/require-description-complete-sentence: 1
    jsdoc/require-hyphen-before-param-description: 1
    jsdoc/require-param: 1
    jsdoc/require-param-description: 1
    jsdoc/require-param-type: 1
    jsdoc/require-returns-description: 1
    jsdoc/require-returns-type: 1
